name: Checking if everything is okay

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Intalling sdkman
        run: curl -s "https://get.sdkman.io" | bash

      - name: Enabling sdkman in terminal
        run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk version && sdk install sbt && sbt test

      - name: Sdk version
        run: sdk version

      - name: Installing sbt
        run: sdk install sbt

      - name: Performing tests
        run: sbt test
