name: Checking if everything is working correctly

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Intalling sdkman
        run: curl -s "https://get.sdkman.io" | bash
      - name: Enabling sdkman in terminal and executing tests
        run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk version && sdk install sbt && sbt compile && sbt test
